### ISSUE TITLE
Configurar ambiente de 'produção'

### ISSUE THREAD

**Issue by saviofreitas** [filipepipeline/spd#2]
Preparar máquinas virtuais de servidor de aplicação e banco de dados.

**Comment by saviofreitas** [comment]
Pessoal, como tinha comentado ontem, nesse artigo tem um lance legal p disponibilizar uma url para teste durante o desenvolvimento:

http://gabrielfeitosa.com/localtunnel-disponibilizando-acesso-uma-aplicacao-local/
e essa é uma alternativa para a solução acima: https://ngrok.com/

Pode ser uma boa para a equipe acompanhar a cara da criança e até para liberar a url a ser utilizada no dia da apresentação.

**Comment by marcelormourao** [comment]
Pessoal, vou dar uma pesquisada aqui sobre load balancer, mas se não conseguir nada posso disponibilizar instâncias na AmazonWS...

**Comment by saviofreitas** [comment]
http://www.haproxy.org/
https://phcco.com/alta-disponibilidade-e-balanceamento-de-carga-http-com-haproxy
http://www.ricardomartins.com.br/2014/04/02/balanceamento-de-carga-com-haproxy/
https://www.digitalocean.com/community/tutorials/an-introduction-to-haproxy-and-load-balancing-concepts

**Comment by saviofreitas** [comment]
Load balance configurado. Iniciando comunicação entre redis e node.
